export const LIST_LIMIT = {
  DEFAULT: 15,
  CAMPAIGN_FIELD: 10,
  BACKER_PLEDGES: 5,
  BACKER_RECENT_PLEDGES: 5,
  DONOR_DONATIONS: 5,
  DONOR_RECENT_DONATIONS: 5,
  USER_BOOKMARKS: 5,
  DONOR_FIELD: 10,
  BACKER_FIELD: 10,
};
